#!/bin/bash

usage() {
    echo "Usage: $0 [cz|us]"
    echo "  cz - Prepnout na CZ (QWERTZ) format"
    echo "  us - Prepnout na Anglickou (en-US) format"
    exit 1
}

# mini-navod, pokud uzivatel nic nezadal
if [ $# -ne 1 ]; then
    usage
fi

# prepnout dle vstupu
case $1 in
    cz)
        setxkbmap cz
        echo "Switched to Czech (QWERTZ) layout"
        ;;
    us)
        setxkbmap us
        echo "Switched to English (US) layout"
        ;;
    *)
        usage
        ;;
esac
